### ISSUE TITLE
Component stopped working

### ISSUE THREAD

**Issue by terryhonn** [thebradleysanders/Kansas_Gas_Home_Assistant#1]
Had been working great, then maybe 10 days ago I started seeing this upon restart of HA:

```
 2020-12-08 09:02:58 ERROR (SyncWorker_13) [custom_components.ks_gas_sensor.sensor] list index out of range

 2020-12-08 09:02:58 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ks_gas_sensor

 Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities await asyncio.gather(*tasks)

 File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity await entity.add_to_platform_finish()

 File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish self.async_write_ha_state()
 File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state self._async_write_ha_state()
 File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state sstate = self.state
 File "/config/custom_components/ks_gas_sensor/sensor.py", line 108, in state return self._state

 AttributeError: 'ks_gas_sensor' object has no attribute '_state'

 2020-12-08 09:02:58 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ks_gas_sensor platform for sensor
 Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 207, in _async_setup_platform await asyncio.gather(*pending)

 File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities await asyncio.gather(*tasks)
 File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity await entity.add_to_platform_finish()
 File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
 self.async_write_ha_state()
 File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
 self._async_write_ha_state()
 File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
 sstate = self.state
 File "/config/custom_components/ks_gas_sensor/sensor.py", line 108, in state
 return self._state
 AttributeError: 'ks_gas_sensor' object has no attribute '_state'

 2020-12-08 09:02:59 ERROR (SyncWorker_23) [custom_components.ks_gas_sensor.sensor] list index out of range

 2020-12-08 09:03:00 ERROR (SyncWorker_13) [custom_components.ks_gas_sensor.sensor] list index out of range

 2020-12-08 09:03:01 ERROR (SyncWorker_1) [custom_components.ks_gas_sensor.sensor] list index out of range

 2020-12-08 09:03:02 ERROR (SyncWorker_18) [custom_components.ks_gas_sensor.sensor] list index out of range

 2020-12-08 09:03:02 ERROR (SyncWorker_4) [custom_components.ks_gas_sensor.sensor] list index out of range
```

I tried changing logging level to debug but didn't seem to change log output.  Glad to help debug if you're still open to working on this.

Thanks!

**Comment by thebradleysanders** [comment]
@terryhonn I will look into this as I also still use this component. Thanks for letting me know.

**Comment by thebradleysanders** [comment]
@terryhonn please update this component and please try again. Please let me know if this fixes your issue.

**Comment by terryhonn** [comment]
> @terryhonn please update this component and please try again. Please let me know if this fixes your issue.

Fixes it perfectly. Thank you very much!

**Comment by thebradleysanders** [comment]
This has been fixed with a new release.
